name: my-keras
channels:
  - defaults
  - conda-forge
  - rdkit
dependencies:
  - python=3.7  # Updated to Python 3.7
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - flask=3.1.0  # Updated Flask to a compatible version
  - werkzeug=3.1.0  # Updated Werkzeug to a compatible version
  - rdkit
  - tensorflow=1.15  # Use TensorFlow 1.15 (compatible with Keras 2.3.1)
  - keras=2.3.1  # Updated Keras to a compatible version
  - pip
  - pip:
      - deepchem
      - protobuf==3.20.1  # Updated protobuf to a compatible version
      - markdown==3.3.6  # Updated markdown
      - tensorflow-gpu==1.15  # Use GPU version if available
      - tensorflow-tensorboard==1.15.0  # Compatible with TensorFlow 1.15
      - tflearn==0.3.2
      - theano==1.0.4
